/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hitachivantara.models.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class laureatesRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2031492478755438815L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"laureatesRecord\",\"namespace\":\"com.hitachivantara.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"firstname\",\"type\":\"string\"},{\"name\":\"surname\",\"type\":\"string\"},{\"name\":\"motivation\",\"type\":\"string\"},{\"name\":\"share\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<laureatesRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<laureatesRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<laureatesRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<laureatesRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<laureatesRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this laureatesRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a laureatesRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a laureatesRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static laureatesRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence firstname;
  private java.lang.CharSequence surname;
  private java.lang.CharSequence motivation;
  private long share;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public laureatesRecord() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param firstname The new value for firstname
   * @param surname The new value for surname
   * @param motivation The new value for motivation
   * @param share The new value for share
   */
  public laureatesRecord(java.lang.Long id, java.lang.CharSequence firstname, java.lang.CharSequence surname, java.lang.CharSequence motivation, java.lang.Long share) {
    this.id = id;
    this.firstname = firstname;
    this.surname = surname;
    this.motivation = motivation;
    this.share = share;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return firstname;
    case 2: return surname;
    case 3: return motivation;
    case 4: return share;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: firstname = (java.lang.CharSequence)value$; break;
    case 2: surname = (java.lang.CharSequence)value$; break;
    case 3: motivation = (java.lang.CharSequence)value$; break;
    case 4: share = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'firstname' field.
   * @return The value of the 'firstname' field.
   */
  public java.lang.CharSequence getFirstname() {
    return firstname;
  }


  /**
   * Sets the value of the 'firstname' field.
   * @param value the value to set.
   */
  public void setFirstname(java.lang.CharSequence value) {
    this.firstname = value;
  }

  /**
   * Gets the value of the 'surname' field.
   * @return The value of the 'surname' field.
   */
  public java.lang.CharSequence getSurname() {
    return surname;
  }


  /**
   * Sets the value of the 'surname' field.
   * @param value the value to set.
   */
  public void setSurname(java.lang.CharSequence value) {
    this.surname = value;
  }

  /**
   * Gets the value of the 'motivation' field.
   * @return The value of the 'motivation' field.
   */
  public java.lang.CharSequence getMotivation() {
    return motivation;
  }


  /**
   * Sets the value of the 'motivation' field.
   * @param value the value to set.
   */
  public void setMotivation(java.lang.CharSequence value) {
    this.motivation = value;
  }

  /**
   * Gets the value of the 'share' field.
   * @return The value of the 'share' field.
   */
  public long getShare() {
    return share;
  }


  /**
   * Sets the value of the 'share' field.
   * @param value the value to set.
   */
  public void setShare(long value) {
    this.share = value;
  }

  /**
   * Creates a new laureatesRecord RecordBuilder.
   * @return A new laureatesRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.laureatesRecord.Builder newBuilder() {
    return new com.hitachivantara.models.avro.laureatesRecord.Builder();
  }

  /**
   * Creates a new laureatesRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new laureatesRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.laureatesRecord.Builder newBuilder(com.hitachivantara.models.avro.laureatesRecord.Builder other) {
    if (other == null) {
      return new com.hitachivantara.models.avro.laureatesRecord.Builder();
    } else {
      return new com.hitachivantara.models.avro.laureatesRecord.Builder(other);
    }
  }

  /**
   * Creates a new laureatesRecord RecordBuilder by copying an existing laureatesRecord instance.
   * @param other The existing instance to copy.
   * @return A new laureatesRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.laureatesRecord.Builder newBuilder(com.hitachivantara.models.avro.laureatesRecord other) {
    if (other == null) {
      return new com.hitachivantara.models.avro.laureatesRecord.Builder();
    } else {
      return new com.hitachivantara.models.avro.laureatesRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for laureatesRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<laureatesRecord>
    implements org.apache.avro.data.RecordBuilder<laureatesRecord> {

    private long id;
    private java.lang.CharSequence firstname;
    private java.lang.CharSequence surname;
    private java.lang.CharSequence motivation;
    private long share;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hitachivantara.models.avro.laureatesRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.firstname)) {
        this.firstname = data().deepCopy(fields()[1].schema(), other.firstname);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.surname)) {
        this.surname = data().deepCopy(fields()[2].schema(), other.surname);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.motivation)) {
        this.motivation = data().deepCopy(fields()[3].schema(), other.motivation);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.share)) {
        this.share = data().deepCopy(fields()[4].schema(), other.share);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing laureatesRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hitachivantara.models.avro.laureatesRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.firstname)) {
        this.firstname = data().deepCopy(fields()[1].schema(), other.firstname);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.surname)) {
        this.surname = data().deepCopy(fields()[2].schema(), other.surname);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.motivation)) {
        this.motivation = data().deepCopy(fields()[3].schema(), other.motivation);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.share)) {
        this.share = data().deepCopy(fields()[4].schema(), other.share);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'firstname' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstname() {
      return firstname;
    }


    /**
      * Sets the value of the 'firstname' field.
      * @param value The value of 'firstname'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder setFirstname(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.firstname = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'firstname' field has been set.
      * @return True if the 'firstname' field has been set, false otherwise.
      */
    public boolean hasFirstname() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'firstname' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder clearFirstname() {
      firstname = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'surname' field.
      * @return The value.
      */
    public java.lang.CharSequence getSurname() {
      return surname;
    }


    /**
      * Sets the value of the 'surname' field.
      * @param value The value of 'surname'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder setSurname(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.surname = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'surname' field has been set.
      * @return True if the 'surname' field has been set, false otherwise.
      */
    public boolean hasSurname() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'surname' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder clearSurname() {
      surname = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'motivation' field.
      * @return The value.
      */
    public java.lang.CharSequence getMotivation() {
      return motivation;
    }


    /**
      * Sets the value of the 'motivation' field.
      * @param value The value of 'motivation'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder setMotivation(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.motivation = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'motivation' field has been set.
      * @return True if the 'motivation' field has been set, false otherwise.
      */
    public boolean hasMotivation() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'motivation' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder clearMotivation() {
      motivation = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'share' field.
      * @return The value.
      */
    public long getShare() {
      return share;
    }


    /**
      * Sets the value of the 'share' field.
      * @param value The value of 'share'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder setShare(long value) {
      validate(fields()[4], value);
      this.share = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'share' field has been set.
      * @return True if the 'share' field has been set, false otherwise.
      */
    public boolean hasShare() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'share' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.laureatesRecord.Builder clearShare() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public laureatesRecord build() {
      try {
        laureatesRecord record = new laureatesRecord();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.firstname = fieldSetFlags()[1] ? this.firstname : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.surname = fieldSetFlags()[2] ? this.surname : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.motivation = fieldSetFlags()[3] ? this.motivation : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.share = fieldSetFlags()[4] ? this.share : (java.lang.Long) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<laureatesRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<laureatesRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<laureatesRecord>
    READER$ = (org.apache.avro.io.DatumReader<laureatesRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.firstname);

    out.writeString(this.surname);

    out.writeString(this.motivation);

    out.writeLong(this.share);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);

      this.surname = in.readString(this.surname instanceof Utf8 ? (Utf8)this.surname : null);

      this.motivation = in.readString(this.motivation instanceof Utf8 ? (Utf8)this.motivation : null);

      this.share = in.readLong();

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.firstname = in.readString(this.firstname instanceof Utf8 ? (Utf8)this.firstname : null);
          break;

        case 2:
          this.surname = in.readString(this.surname instanceof Utf8 ? (Utf8)this.surname : null);
          break;

        case 3:
          this.motivation = in.readString(this.motivation instanceof Utf8 ? (Utf8)this.motivation : null);
          break;

        case 4:
          this.share = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










