/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.hitachivantara.models.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class metaRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6186201057714523872L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"metaRecord\",\"namespace\":\"com.hitachivantara.avro\",\"fields\":[{\"name\":\"limit\",\"type\":\"long\"},{\"name\":\"offset\",\"type\":\"long\"},{\"name\":\"total_count\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<metaRecord> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<metaRecord> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<metaRecord> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<metaRecord> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<metaRecord> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this metaRecord to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a metaRecord from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a metaRecord instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static metaRecord fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long limit;
  private long offset;
  private long total_count;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public metaRecord() {}

  /**
   * All-args constructor.
   * @param limit The new value for limit
   * @param offset The new value for offset
   * @param total_count The new value for total_count
   */
  public metaRecord(java.lang.Long limit, java.lang.Long offset, java.lang.Long total_count) {
    this.limit = limit;
    this.offset = offset;
    this.total_count = total_count;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return limit;
    case 1: return offset;
    case 2: return total_count;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: limit = (java.lang.Long)value$; break;
    case 1: offset = (java.lang.Long)value$; break;
    case 2: total_count = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'limit' field.
   * @return The value of the 'limit' field.
   */
  public long getLimit() {
    return limit;
  }


  /**
   * Sets the value of the 'limit' field.
   * @param value the value to set.
   */
  public void setLimit(long value) {
    this.limit = value;
  }

  /**
   * Gets the value of the 'offset' field.
   * @return The value of the 'offset' field.
   */
  public long getOffset() {
    return offset;
  }


  /**
   * Sets the value of the 'offset' field.
   * @param value the value to set.
   */
  public void setOffset(long value) {
    this.offset = value;
  }

  /**
   * Gets the value of the 'total_count' field.
   * @return The value of the 'total_count' field.
   */
  public long getTotalCount() {
    return total_count;
  }


  /**
   * Sets the value of the 'total_count' field.
   * @param value the value to set.
   */
  public void setTotalCount(long value) {
    this.total_count = value;
  }

  /**
   * Creates a new metaRecord RecordBuilder.
   * @return A new metaRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.metaRecord.Builder newBuilder() {
    return new com.hitachivantara.models.avro.metaRecord.Builder();
  }

  /**
   * Creates a new metaRecord RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new metaRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.metaRecord.Builder newBuilder(com.hitachivantara.models.avro.metaRecord.Builder other) {
    if (other == null) {
      return new com.hitachivantara.models.avro.metaRecord.Builder();
    } else {
      return new com.hitachivantara.models.avro.metaRecord.Builder(other);
    }
  }

  /**
   * Creates a new metaRecord RecordBuilder by copying an existing metaRecord instance.
   * @param other The existing instance to copy.
   * @return A new metaRecord RecordBuilder
   */
  public static com.hitachivantara.models.avro.metaRecord.Builder newBuilder(com.hitachivantara.models.avro.metaRecord other) {
    if (other == null) {
      return new com.hitachivantara.models.avro.metaRecord.Builder();
    } else {
      return new com.hitachivantara.models.avro.metaRecord.Builder(other);
    }
  }

  /**
   * RecordBuilder for metaRecord instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<metaRecord>
    implements org.apache.avro.data.RecordBuilder<metaRecord> {

    private long limit;
    private long offset;
    private long total_count;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.hitachivantara.models.avro.metaRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.limit)) {
        this.limit = data().deepCopy(fields()[0].schema(), other.limit);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.offset)) {
        this.offset = data().deepCopy(fields()[1].schema(), other.offset);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.total_count)) {
        this.total_count = data().deepCopy(fields()[2].schema(), other.total_count);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing metaRecord instance
     * @param other The existing instance to copy.
     */
    private Builder(com.hitachivantara.models.avro.metaRecord other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.limit)) {
        this.limit = data().deepCopy(fields()[0].schema(), other.limit);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.offset)) {
        this.offset = data().deepCopy(fields()[1].schema(), other.offset);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.total_count)) {
        this.total_count = data().deepCopy(fields()[2].schema(), other.total_count);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'limit' field.
      * @return The value.
      */
    public long getLimit() {
      return limit;
    }


    /**
      * Sets the value of the 'limit' field.
      * @param value The value of 'limit'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder setLimit(long value) {
      validate(fields()[0], value);
      this.limit = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'limit' field has been set.
      * @return True if the 'limit' field has been set, false otherwise.
      */
    public boolean hasLimit() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'limit' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder clearLimit() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'offset' field.
      * @return The value.
      */
    public long getOffset() {
      return offset;
    }


    /**
      * Sets the value of the 'offset' field.
      * @param value The value of 'offset'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder setOffset(long value) {
      validate(fields()[1], value);
      this.offset = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'offset' field has been set.
      * @return True if the 'offset' field has been set, false otherwise.
      */
    public boolean hasOffset() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'offset' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder clearOffset() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'total_count' field.
      * @return The value.
      */
    public long getTotalCount() {
      return total_count;
    }


    /**
      * Sets the value of the 'total_count' field.
      * @param value The value of 'total_count'.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder setTotalCount(long value) {
      validate(fields()[2], value);
      this.total_count = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'total_count' field has been set.
      * @return True if the 'total_count' field has been set, false otherwise.
      */
    public boolean hasTotalCount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'total_count' field.
      * @return This builder.
      */
    public com.hitachivantara.models.avro.metaRecord.Builder clearTotalCount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public metaRecord build() {
      try {
        metaRecord record = new metaRecord();
        record.limit = fieldSetFlags()[0] ? this.limit : (java.lang.Long) defaultValue(fields()[0]);
        record.offset = fieldSetFlags()[1] ? this.offset : (java.lang.Long) defaultValue(fields()[1]);
        record.total_count = fieldSetFlags()[2] ? this.total_count : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<metaRecord>
    WRITER$ = (org.apache.avro.io.DatumWriter<metaRecord>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<metaRecord>
    READER$ = (org.apache.avro.io.DatumReader<metaRecord>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.limit);

    out.writeLong(this.offset);

    out.writeLong(this.total_count);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.limit = in.readLong();

      this.offset = in.readLong();

      this.total_count = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.limit = in.readLong();
          break;

        case 1:
          this.offset = in.readLong();
          break;

        case 2:
          this.total_count = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










