// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movie.proto

package com.hitachivantara.models.proto;

public final class Movie {
  private Movie() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hitachivantara.proto.MovieMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested> 
        getItemsList();
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    com.hitachivantara.models.proto.Movie.MovieMessage.Nested getItems(int index);
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    java.util.List<? extends com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.hitachivantara.proto.MovieMessage}
   */
  public static final class MovieMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hitachivantara.proto.MovieMessage)
      MovieMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MovieMessage.newBuilder() to construct.
    private MovieMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieMessage() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MovieMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MovieMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<com.hitachivantara.models.proto.Movie.MovieMessage.Nested>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.hitachivantara.models.proto.Movie.MovieMessage.Nested.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hitachivantara.models.proto.Movie.MovieMessage.class, com.hitachivantara.models.proto.Movie.MovieMessage.Builder.class);
    }

    public interface NestedOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.hitachivantara.proto.MovieMessage.Nested)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      java.lang.String getTitle();
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>uint64 year = 2;</code>
       * @return The year.
       */
      long getYear();

      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      java.util.List<com.google.protobuf.Any> 
          getCastList();
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      com.google.protobuf.Any getCast(int index);
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      int getCastCount();
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
          getCastOrBuilderList();
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      com.google.protobuf.AnyOrBuilder getCastOrBuilder(
          int index);

      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      java.util.List<com.google.protobuf.Any> 
          getGenresList();
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      com.google.protobuf.Any getGenres(int index);
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      int getGenresCount();
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
          getGenresOrBuilderList();
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      com.google.protobuf.AnyOrBuilder getGenresOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code com.hitachivantara.proto.MovieMessage.Nested}
     */
    public static final class Nested extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.hitachivantara.proto.MovieMessage.Nested)
        NestedOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Nested.newBuilder() to construct.
      private Nested(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Nested() {
        title_ = "";
        cast_ = java.util.Collections.emptyList();
        genres_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Nested();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Nested(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                title_ = s;
                break;
              }
              case 16: {

                year_ = input.readUInt64();
                break;
              }
              case 26: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  cast_ = new java.util.ArrayList<com.google.protobuf.Any>();
                  mutable_bitField0_ |= 0x00000001;
                }
                cast_.add(
                    input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                break;
              }
              case 34: {
                if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                  genres_ = new java.util.ArrayList<com.google.protobuf.Any>();
                  mutable_bitField0_ |= 0x00000002;
                }
                genres_.add(
                    input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            cast_ = java.util.Collections.unmodifiableList(cast_);
          }
          if (((mutable_bitField0_ & 0x00000002) != 0)) {
            genres_ = java.util.Collections.unmodifiableList(genres_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_Nested_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hitachivantara.models.proto.Movie.MovieMessage.Nested.class, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder.class);
      }

      public static final int TITLE_FIELD_NUMBER = 1;
      private volatile java.lang.Object title_;
      /**
       * <code>string title = 1;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        }
      }
      /**
       * <code>string title = 1;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int YEAR_FIELD_NUMBER = 2;
      private long year_;
      /**
       * <code>uint64 year = 2;</code>
       * @return The year.
       */
      @java.lang.Override
      public long getYear() {
        return year_;
      }

      public static final int CAST_FIELD_NUMBER = 3;
      private java.util.List<com.google.protobuf.Any> cast_;
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      @java.lang.Override
      public java.util.List<com.google.protobuf.Any> getCastList() {
        return cast_;
      }
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      @java.lang.Override
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
          getCastOrBuilderList() {
        return cast_;
      }
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      @java.lang.Override
      public int getCastCount() {
        return cast_.size();
      }
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Any getCast(int index) {
        return cast_.get(index);
      }
      /**
       * <code>repeated .google.protobuf.Any cast = 3;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getCastOrBuilder(
          int index) {
        return cast_.get(index);
      }

      public static final int GENRES_FIELD_NUMBER = 4;
      private java.util.List<com.google.protobuf.Any> genres_;
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      @java.lang.Override
      public java.util.List<com.google.protobuf.Any> getGenresList() {
        return genres_;
      }
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      @java.lang.Override
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
          getGenresOrBuilderList() {
        return genres_;
      }
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      @java.lang.Override
      public int getGenresCount() {
        return genres_.size();
      }
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.Any getGenres(int index) {
        return genres_.get(index);
      }
      /**
       * <code>repeated .google.protobuf.Any genres = 4;</code>
       */
      @java.lang.Override
      public com.google.protobuf.AnyOrBuilder getGenresOrBuilder(
          int index) {
        return genres_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
        }
        if (year_ != 0L) {
          output.writeUInt64(2, year_);
        }
        for (int i = 0; i < cast_.size(); i++) {
          output.writeMessage(3, cast_.get(i));
        }
        for (int i = 0; i < genres_.size(); i++) {
          output.writeMessage(4, genres_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
        }
        if (year_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(2, year_);
        }
        for (int i = 0; i < cast_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, cast_.get(i));
        }
        for (int i = 0; i < genres_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, genres_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.hitachivantara.models.proto.Movie.MovieMessage.Nested)) {
          return super.equals(obj);
        }
        com.hitachivantara.models.proto.Movie.MovieMessage.Nested other = (com.hitachivantara.models.proto.Movie.MovieMessage.Nested) obj;

        if (!getTitle()
            .equals(other.getTitle())) return false;
        if (getYear()
            != other.getYear()) return false;
        if (!getCastList()
            .equals(other.getCastList())) return false;
        if (!getGenresList()
            .equals(other.getGenresList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
        hash = (37 * hash) + YEAR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getYear());
        if (getCastCount() > 0) {
          hash = (37 * hash) + CAST_FIELD_NUMBER;
          hash = (53 * hash) + getCastList().hashCode();
        }
        if (getGenresCount() > 0) {
          hash = (37 * hash) + GENRES_FIELD_NUMBER;
          hash = (53 * hash) + getGenresList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.hitachivantara.models.proto.Movie.MovieMessage.Nested prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.hitachivantara.proto.MovieMessage.Nested}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.hitachivantara.proto.MovieMessage.Nested)
          com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_Nested_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.hitachivantara.models.proto.Movie.MovieMessage.Nested.class, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder.class);
        }

        // Construct using com.hitachivantara.proto.Movie.MovieMessage.Nested.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getCastFieldBuilder();
            getGenresFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          title_ = "";

          year_ = 0L;

          if (castBuilder_ == null) {
            cast_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            castBuilder_.clear();
          }
          if (genresBuilder_ == null) {
            genres_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            genresBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor;
        }

        @java.lang.Override
        public com.hitachivantara.models.proto.Movie.MovieMessage.Nested getDefaultInstanceForType() {
          return com.hitachivantara.models.proto.Movie.MovieMessage.Nested.getDefaultInstance();
        }

        @java.lang.Override
        public com.hitachivantara.models.proto.Movie.MovieMessage.Nested build() {
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.hitachivantara.models.proto.Movie.MovieMessage.Nested buildPartial() {
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested result = new com.hitachivantara.models.proto.Movie.MovieMessage.Nested(this);
          int from_bitField0_ = bitField0_;
          result.title_ = title_;
          result.year_ = year_;
          if (castBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              cast_ = java.util.Collections.unmodifiableList(cast_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.cast_ = cast_;
          } else {
            result.cast_ = castBuilder_.build();
          }
          if (genresBuilder_ == null) {
            if (((bitField0_ & 0x00000002) != 0)) {
              genres_ = java.util.Collections.unmodifiableList(genres_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.genres_ = genres_;
          } else {
            result.genres_ = genresBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.hitachivantara.models.proto.Movie.MovieMessage.Nested) {
            return mergeFrom((com.hitachivantara.models.proto.Movie.MovieMessage.Nested)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.hitachivantara.models.proto.Movie.MovieMessage.Nested other) {
          if (other == com.hitachivantara.models.proto.Movie.MovieMessage.Nested.getDefaultInstance()) return this;
          if (!other.getTitle().isEmpty()) {
            title_ = other.title_;
            onChanged();
          }
          if (other.getYear() != 0L) {
            setYear(other.getYear());
          }
          if (castBuilder_ == null) {
            if (!other.cast_.isEmpty()) {
              if (cast_.isEmpty()) {
                cast_ = other.cast_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensureCastIsMutable();
                cast_.addAll(other.cast_);
              }
              onChanged();
            }
          } else {
            if (!other.cast_.isEmpty()) {
              if (castBuilder_.isEmpty()) {
                castBuilder_.dispose();
                castBuilder_ = null;
                cast_ = other.cast_;
                bitField0_ = (bitField0_ & ~0x00000001);
                castBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getCastFieldBuilder() : null;
              } else {
                castBuilder_.addAllMessages(other.cast_);
              }
            }
          }
          if (genresBuilder_ == null) {
            if (!other.genres_.isEmpty()) {
              if (genres_.isEmpty()) {
                genres_ = other.genres_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureGenresIsMutable();
                genres_.addAll(other.genres_);
              }
              onChanged();
            }
          } else {
            if (!other.genres_.isEmpty()) {
              if (genresBuilder_.isEmpty()) {
                genresBuilder_.dispose();
                genresBuilder_ = null;
                genres_ = other.genres_;
                bitField0_ = (bitField0_ & ~0x00000002);
                genresBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getGenresFieldBuilder() : null;
              } else {
                genresBuilder_.addAllMessages(other.genres_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.hitachivantara.models.proto.Movie.MovieMessage.Nested) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object title_ = "";
        /**
         * <code>string title = 1;</code>
         * @return The title.
         */
        public java.lang.String getTitle() {
          java.lang.Object ref = title_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            title_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string title = 1;</code>
         * @return The bytes for title.
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          java.lang.Object ref = title_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            title_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string title = 1;</code>
         * @param value The title to set.
         * @return This builder for chaining.
         */
        public Builder setTitle(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          title_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string title = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTitle() {
          
          title_ = getDefaultInstance().getTitle();
          onChanged();
          return this;
        }
        /**
         * <code>string title = 1;</code>
         * @param value The bytes for title to set.
         * @return This builder for chaining.
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          title_ = value;
          onChanged();
          return this;
        }

        private long year_ ;
        /**
         * <code>uint64 year = 2;</code>
         * @return The year.
         */
        @java.lang.Override
        public long getYear() {
          return year_;
        }
        /**
         * <code>uint64 year = 2;</code>
         * @param value The year to set.
         * @return This builder for chaining.
         */
        public Builder setYear(long value) {
          
          year_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint64 year = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearYear() {
          
          year_ = 0L;
          onChanged();
          return this;
        }

        private java.util.List<com.google.protobuf.Any> cast_ =
          java.util.Collections.emptyList();
        private void ensureCastIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            cast_ = new java.util.ArrayList<com.google.protobuf.Any>(cast_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> castBuilder_;

        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public java.util.List<com.google.protobuf.Any> getCastList() {
          if (castBuilder_ == null) {
            return java.util.Collections.unmodifiableList(cast_);
          } else {
            return castBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public int getCastCount() {
          if (castBuilder_ == null) {
            return cast_.size();
          } else {
            return castBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public com.google.protobuf.Any getCast(int index) {
          if (castBuilder_ == null) {
            return cast_.get(index);
          } else {
            return castBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder setCast(
            int index, com.google.protobuf.Any value) {
          if (castBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCastIsMutable();
            cast_.set(index, value);
            onChanged();
          } else {
            castBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder setCast(
            int index, com.google.protobuf.Any.Builder builderForValue) {
          if (castBuilder_ == null) {
            ensureCastIsMutable();
            cast_.set(index, builderForValue.build());
            onChanged();
          } else {
            castBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder addCast(com.google.protobuf.Any value) {
          if (castBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCastIsMutable();
            cast_.add(value);
            onChanged();
          } else {
            castBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder addCast(
            int index, com.google.protobuf.Any value) {
          if (castBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureCastIsMutable();
            cast_.add(index, value);
            onChanged();
          } else {
            castBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder addCast(
            com.google.protobuf.Any.Builder builderForValue) {
          if (castBuilder_ == null) {
            ensureCastIsMutable();
            cast_.add(builderForValue.build());
            onChanged();
          } else {
            castBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder addCast(
            int index, com.google.protobuf.Any.Builder builderForValue) {
          if (castBuilder_ == null) {
            ensureCastIsMutable();
            cast_.add(index, builderForValue.build());
            onChanged();
          } else {
            castBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder addAllCast(
            java.lang.Iterable<? extends com.google.protobuf.Any> values) {
          if (castBuilder_ == null) {
            ensureCastIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, cast_);
            onChanged();
          } else {
            castBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder clearCast() {
          if (castBuilder_ == null) {
            cast_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            castBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public Builder removeCast(int index) {
          if (castBuilder_ == null) {
            ensureCastIsMutable();
            cast_.remove(index);
            onChanged();
          } else {
            castBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public com.google.protobuf.Any.Builder getCastBuilder(
            int index) {
          return getCastFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public com.google.protobuf.AnyOrBuilder getCastOrBuilder(
            int index) {
          if (castBuilder_ == null) {
            return cast_.get(index);  } else {
            return castBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
             getCastOrBuilderList() {
          if (castBuilder_ != null) {
            return castBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(cast_);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public com.google.protobuf.Any.Builder addCastBuilder() {
          return getCastFieldBuilder().addBuilder(
              com.google.protobuf.Any.getDefaultInstance());
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public com.google.protobuf.Any.Builder addCastBuilder(
            int index) {
          return getCastFieldBuilder().addBuilder(
              index, com.google.protobuf.Any.getDefaultInstance());
        }
        /**
         * <code>repeated .google.protobuf.Any cast = 3;</code>
         */
        public java.util.List<com.google.protobuf.Any.Builder> 
             getCastBuilderList() {
          return getCastFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
            getCastFieldBuilder() {
          if (castBuilder_ == null) {
            castBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                    cast_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            cast_ = null;
          }
          return castBuilder_;
        }

        private java.util.List<com.google.protobuf.Any> genres_ =
          java.util.Collections.emptyList();
        private void ensureGenresIsMutable() {
          if (!((bitField0_ & 0x00000002) != 0)) {
            genres_ = new java.util.ArrayList<com.google.protobuf.Any>(genres_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> genresBuilder_;

        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public java.util.List<com.google.protobuf.Any> getGenresList() {
          if (genresBuilder_ == null) {
            return java.util.Collections.unmodifiableList(genres_);
          } else {
            return genresBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public int getGenresCount() {
          if (genresBuilder_ == null) {
            return genres_.size();
          } else {
            return genresBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public com.google.protobuf.Any getGenres(int index) {
          if (genresBuilder_ == null) {
            return genres_.get(index);
          } else {
            return genresBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder setGenres(
            int index, com.google.protobuf.Any value) {
          if (genresBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureGenresIsMutable();
            genres_.set(index, value);
            onChanged();
          } else {
            genresBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder setGenres(
            int index, com.google.protobuf.Any.Builder builderForValue) {
          if (genresBuilder_ == null) {
            ensureGenresIsMutable();
            genres_.set(index, builderForValue.build());
            onChanged();
          } else {
            genresBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder addGenres(com.google.protobuf.Any value) {
          if (genresBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureGenresIsMutable();
            genres_.add(value);
            onChanged();
          } else {
            genresBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder addGenres(
            int index, com.google.protobuf.Any value) {
          if (genresBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureGenresIsMutable();
            genres_.add(index, value);
            onChanged();
          } else {
            genresBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder addGenres(
            com.google.protobuf.Any.Builder builderForValue) {
          if (genresBuilder_ == null) {
            ensureGenresIsMutable();
            genres_.add(builderForValue.build());
            onChanged();
          } else {
            genresBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder addGenres(
            int index, com.google.protobuf.Any.Builder builderForValue) {
          if (genresBuilder_ == null) {
            ensureGenresIsMutable();
            genres_.add(index, builderForValue.build());
            onChanged();
          } else {
            genresBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder addAllGenres(
            java.lang.Iterable<? extends com.google.protobuf.Any> values) {
          if (genresBuilder_ == null) {
            ensureGenresIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, genres_);
            onChanged();
          } else {
            genresBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder clearGenres() {
          if (genresBuilder_ == null) {
            genres_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            genresBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public Builder removeGenres(int index) {
          if (genresBuilder_ == null) {
            ensureGenresIsMutable();
            genres_.remove(index);
            onChanged();
          } else {
            genresBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public com.google.protobuf.Any.Builder getGenresBuilder(
            int index) {
          return getGenresFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public com.google.protobuf.AnyOrBuilder getGenresOrBuilder(
            int index) {
          if (genresBuilder_ == null) {
            return genres_.get(index);  } else {
            return genresBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
             getGenresOrBuilderList() {
          if (genresBuilder_ != null) {
            return genresBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(genres_);
          }
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public com.google.protobuf.Any.Builder addGenresBuilder() {
          return getGenresFieldBuilder().addBuilder(
              com.google.protobuf.Any.getDefaultInstance());
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public com.google.protobuf.Any.Builder addGenresBuilder(
            int index) {
          return getGenresFieldBuilder().addBuilder(
              index, com.google.protobuf.Any.getDefaultInstance());
        }
        /**
         * <code>repeated .google.protobuf.Any genres = 4;</code>
         */
        public java.util.List<com.google.protobuf.Any.Builder> 
             getGenresBuilderList() {
          return getGenresFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
            getGenresFieldBuilder() {
          if (genresBuilder_ == null) {
            genresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                    genres_,
                    ((bitField0_ & 0x00000002) != 0),
                    getParentForChildren(),
                    isClean());
            genres_ = null;
          }
          return genresBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.hitachivantara.proto.MovieMessage.Nested)
      }

      // @@protoc_insertion_point(class_scope:com.hitachivantara.proto.MovieMessage.Nested)
      private static final com.hitachivantara.models.proto.Movie.MovieMessage.Nested DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.hitachivantara.models.proto.Movie.MovieMessage.Nested();
      }

      public static com.hitachivantara.models.proto.Movie.MovieMessage.Nested getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Nested>
          PARSER = new com.google.protobuf.AbstractParser<Nested>() {
        @java.lang.Override
        public Nested parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Nested(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Nested> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Nested> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.hitachivantara.models.proto.Movie.MovieMessage.Nested getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested> items_;
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    @java.lang.Override
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    @java.lang.Override
    public com.hitachivantara.models.proto.Movie.MovieMessage.Nested getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
     */
    @java.lang.Override
    public com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hitachivantara.models.proto.Movie.MovieMessage)) {
        return super.equals(obj);
      }
      com.hitachivantara.models.proto.Movie.MovieMessage other = (com.hitachivantara.models.proto.Movie.MovieMessage) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hitachivantara.models.proto.Movie.MovieMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hitachivantara.models.proto.Movie.MovieMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hitachivantara.proto.MovieMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hitachivantara.proto.MovieMessage)
        com.hitachivantara.models.proto.Movie.MovieMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hitachivantara.models.proto.Movie.MovieMessage.class, com.hitachivantara.models.proto.Movie.MovieMessage.Builder.class);
      }

      // Construct using com.hitachivantara.proto.Movie.MovieMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hitachivantara.models.proto.Movie.internal_static_com_hitachivantara_proto_MovieMessage_descriptor;
      }

      @java.lang.Override
      public com.hitachivantara.models.proto.Movie.MovieMessage getDefaultInstanceForType() {
        return com.hitachivantara.models.proto.Movie.MovieMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.hitachivantara.models.proto.Movie.MovieMessage build() {
        com.hitachivantara.models.proto.Movie.MovieMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hitachivantara.models.proto.Movie.MovieMessage buildPartial() {
        com.hitachivantara.models.proto.Movie.MovieMessage result = new com.hitachivantara.models.proto.Movie.MovieMessage(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hitachivantara.models.proto.Movie.MovieMessage) {
          return mergeFrom((com.hitachivantara.models.proto.Movie.MovieMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hitachivantara.models.proto.Movie.MovieMessage other) {
        if (other == com.hitachivantara.models.proto.Movie.MovieMessage.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hitachivantara.models.proto.Movie.MovieMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hitachivantara.models.proto.Movie.MovieMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.hitachivantara.models.proto.Movie.MovieMessage.Nested>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder, com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public com.hitachivantara.models.proto.Movie.MovieMessage.Nested getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder setItems(
          int index, com.hitachivantara.models.proto.Movie.MovieMessage.Nested value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder setItems(
          int index, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder addItems(com.hitachivantara.models.proto.Movie.MovieMessage.Nested value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder addItems(
          int index, com.hitachivantara.models.proto.Movie.MovieMessage.Nested value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder addItems(
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder addItems(
          int index, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.hitachivantara.models.proto.Movie.MovieMessage.Nested> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public java.util.List<? extends com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.hitachivantara.models.proto.Movie.MovieMessage.Nested.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hitachivantara.proto.MovieMessage.Nested items = 1;</code>
       */
      public java.util.List<com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hitachivantara.models.proto.Movie.MovieMessage.Nested, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder, com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.hitachivantara.models.proto.Movie.MovieMessage.Nested, com.hitachivantara.models.proto.Movie.MovieMessage.Nested.Builder, com.hitachivantara.models.proto.Movie.MovieMessage.NestedOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hitachivantara.proto.MovieMessage)
    }

    // @@protoc_insertion_point(class_scope:com.hitachivantara.proto.MovieMessage)
    private static final com.hitachivantara.models.proto.Movie.MovieMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hitachivantara.models.proto.Movie.MovieMessage();
    }

    public static com.hitachivantara.models.proto.Movie.MovieMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieMessage>
        PARSER = new com.google.protobuf.AbstractParser<MovieMessage>() {
      @java.lang.Override
      public MovieMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MovieMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hitachivantara.models.proto.Movie.MovieMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hitachivantara_proto_MovieMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hitachivantara_proto_MovieMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hitachivantara_proto_MovieMessage_Nested_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013movie.proto\022\030com.hitachivantara.proto\032" +
      "\031google/protobuf/any.proto\"\275\001\n\014MovieMess" +
      "age\022<\n\005items\030\001 \003(\0132-.com.hitachivantara." +
      "proto.MovieMessage.Nested\032o\n\006Nested\022\r\n\005t" +
      "itle\030\001 \001(\t\022\014\n\004year\030\002 \001(\004\022\"\n\004cast\030\003 \003(\0132\024" +
      ".google.protobuf.Any\022$\n\006genres\030\004 \003(\0132\024.g" +
      "oogle.protobuf.AnyB\032\n\030com.hitachivantara" +
      ".protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_com_hitachivantara_proto_MovieMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hitachivantara_proto_MovieMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hitachivantara_proto_MovieMessage_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor =
      internal_static_com_hitachivantara_proto_MovieMessage_descriptor.getNestedTypes().get(0);
    internal_static_com_hitachivantara_proto_MovieMessage_Nested_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hitachivantara_proto_MovieMessage_Nested_descriptor,
        new java.lang.String[] { "Title", "Year", "Cast", "Genres", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
